Systemd changes and 10.01.06 update
TexasInstruments/ti-bdebstrap pull request #61
Opened 2024-11-11 05:21 UTC by jsuhaas22

This PR does 3 things:

1. Adds systemd-networkd as the default network manager instead of NetworkManager. Since we are adding support for wifi cards, we need wpasupplicant. However, wpasupplicant breaks NetworkManager. So disable NetworkManager by default, and use systemd-networkd instead, which works well with wpasupplicant.
2. Install and enable Seatd service. Weston-14 doesn't work without it.
3. Bump up to 10.01.06 tag.

2024-11-11 05:42 UTC, cshilwant reviewed
Why aren't we updating bookworm to 10.01 baseline?

2024-11-11 05:49 UTC, cshilwant requested changes
We also need the 10.01.06 toml file right? Else workflows would fail.

2024-11-11 05:50 UTC, jsuhaas22 commented
@cshilwant Bookworm upstream uses 6.1 baseline. It is the "stable" release. We are following the upstream here. It wasn't updated to 10.0 either, since we moved to 6.6 in 10.0.

2024-11-12 05:33 UTC, cshilwant approved these changes

2024-11-18 08:57 UTC, merged